name: Check Draft Release

on:
  release:
    types:
      - published
      - edited

jobs:
  check_draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get draft release
        id: release
        uses: actions/github-script@v4
        with:
          script: |
            const response = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'draft'  # Replace 'draft' with your actual draft release tag
            });

            console.log(response.data.upload_url);
            console.log(response.data.assets);

            return response.data

      - name: Check file in draft release
        id: check_file
        run: |
          # Get the file names in the draft release
          files=$(echo "${{ steps.release.outputs.assets }}" | jq -r '.[].name')

          # Check if the desired file exists
          if [[ $files =~ 'desired_file_name.ext' ]]; then
            echo "The file exists in the draft release"
            echo "::set-output name=file_exists::true"
          else
            echo "The file does not exist in the draft release"
            echo "::set-output name=file_exists::false"
          fi

      - name: Trigger Publish Workflow
        if: steps.check_file.outputs.file_exists == 'true'
        run: |
          echo "File exists in the draft release. Triggering Publish Workflow."
          echo "::set-output name=trigger_publish::true"
