name: Check Draft Release Assets
on:
  workflow_dispatch:

jobs:
  check_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Draft Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest draft release
          draft_release=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/releases | \
              jq -r 'map(select(.draft))[0] | .tag_name')

          # Check if the draft release exists and is not published yet
          if [[ -n "$draft_release" ]]; then
            echo "Latest draft release: $draft_release"

            # Get the assets for the draft release
            assets=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/releases/tags/$draft_release/assets | \
              jq -r '.[].name')

            # Check if the required asset exists
            required_asset="terraform-provider-oneview_8.3.0-13_SHA256SUMS.sig"
            if echo "$assets" | grep -q "$required_asset"; then
              echo "Required asset '$required_asset' found in the draft release!"
            else
              echo "Required asset '$required_asset' not found in the draft release."
              exit 1
            fi
          else
            echo "No draft releases found."
            exit 1
          fi
