name: Check Draft Release

on:
  workflow_dispatch:

jobs:
  check_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Get draft release ID
      id: v8.4.0-13
      run: |
        draft_release_id=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases" \
          | jq -r '.[] | select(.draft == true) | .id')
        echo "::set-output name=draft_release_id::$draft_release_id"
    
    - name: Check if file exists
      id: terraform-provider-oneview_8.3.0-13_SHA256SUMS.sig
      run: |
        draft_release_id=${{ needs.draft_release.outputs.draft_release_id }}
        file_exists=$(curl --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/releases/$draft_release_id/assets" \
          | jq -r '.[] | select(.name == "your-file-name") | .id')
        echo "::set-output name=file_exists::$file_exists"
    
    - name: Output result
      run: |
        file_exists=${{ needs.check_file.outputs.file_exists }}
        if [[ $file_exists ]]; then
          echo "The file exists in the draft release."
        else
          echo "The file does not exist in the draft release."
        fi
