name: Upload Provider to Terraform Registry

on:
  push:
    branches:
      - master

jobs:
  upload_provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Install necessary dependencies (e.g., Git)
          # Replace with the appropriate package manager for your operating system

      - name: Publish Provider
        env:
          TERRAFORM_REGISTRY_TOKEN: ${{ secrets.PAT_TOKEN }}
          PROVIDER_NAME: akshith-gunasheelan/oneview
          PROVIDER_VERSION: v8.4.0-13
        run: |
          # Authenticate with the Terraform Registry
          curl --request POST \
            --header "Authorization: Bearer $TERRAFORM_REGISTRY_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "type": "providers",
                "attributes": {
                  "name": "'"$PROVIDER_NAME"'",
                  "vcs-repo": {
                    "identifier": "'"$GITHUB_REPOSITORY"'",
                    "display_identifier": "'"$GITHUB_REPOSITORY"'",
                    "type": "github",
                    "actions_allowed": true
                  }
                }
              }
            }' \
            --url "https://registry.terraform.io/v1/providers"

          # Publish the provider version
          curl --request POST \
            --header "Authorization: Bearer $TERRAFORM_REGISTRY_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "type": "versions",
                "attributes": {
                  "version": "'"$PROVIDER_VERSION"'",
                  "vcs-ref": "'"$GITHUB_SHA"'"
                }
              }
            }' \
            --url "https://registry.terraform.io/v1/providers/$PROVIDER_NAME/versions"
