name: Upload Provider to Terraform Registry

on:
  push:
    branches:
      - master

jobs:
  upload_provider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          # Install necessary dependencies (e.g., Git)
          # Replace with the appropriate package manager for your operating system

      - name: Publish Provider
        env:
          TERRAFORM_REGISTRY_TOKEN: ${{ secrets.TERRAFORM_REGISTRY_TOKEN }}
          PROVIDER_NAME: akshith-gunasheelan/oneview 
        run: |
          # Authenticate with the Terraform Registry
          curl --request POST \
            --header "Authorization: Bearer $TERRAFORM_REGISTRY_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "type": "providers",
                "attributes": {
                  "name": "'"$PROVIDER_NAME"'",
                  "namespace": "namespace"
                }
              }
            }' \
            --url "https://registry.terraform.io/v1/providers"

          # Publish the provider version
          curl --request POST \
            --header "Authorization: Bearer $TERRAFORM_REGISTRY_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --data '{
              "data": {
                "type": "versions",
                "attributes": {
                  "version": "8.4.0-13",
                  "provider": "akshith-gunasheelan/oneview ",
                  "protocols": ["5.0"]
                }
              }
            }' \
            --url "https://registry.terraform.io/v1/providers/<namespace>/provider-name/versions"
